### ISSUE TITLE
Webhooks URLs are generated with "localhost" instead of "domain names" 

### ISSUE THREAD

**Issue by thinkmojo** [UnlyEd/n8n-heroku-demo#1]
Hello, thanks for this repo, this is really great!

I'm having an issue though with the webhook URLs auto-generated when creating a new node. This gives something like:

"http://localhost:20832/webhook/c2448fb0-f6e4-4b93-b134-f6dcb0012894". 

But my understanding the "http://localhost:20832" should actually be the domain name or the IP address of the server. I can't seem to find a way around this, which makes the webhooks never receiving any messages from external apps. (The demo at https://unly-n8n-demo.herokuapp.com/ does the same thing too).    

Here's a quick screen recording:

https://www.loom.com/share/19e226354bf343458122680b2ff287f4

Am I missing something? Is there some kind of variable to setup somewhere to make it work? Hopefully someone would have some pointers! 

Thanks a lot!

**Comment by vongohren** [comment]
Im just supporting this and posting a link to the place I commented on this: https://github.com/sarveshpro/n8n-heroku/issues/16#issuecomment-778853523

How can we get the right webhook url on this @Vadorequest

**Comment by Vadorequest** [comment]
I've no idea. I didn't notice this, and this fork aimed at fixing the Heroku installation, I wasn't aware of this bug (it's definitely not right).

I won't have time to look into it, I was interested in a Heroku setup to see if I could avoid paying for the n8n hosted plans, but I'm still using a n8n hosted plan and having this as a side project to see if it's viable, if ever the n8n hosted solution doesn't work for us and we'd need to migrate to something self-hosted.

**Comment by Vadorequest** [comment]
I suggest opening an issue on the origin repo at https://github.com/sarveshpro/n8n-heroku/issues, I'll keep this one open until the issue is fixed. :)

**Comment by vongohren** [comment]
All can be closed now, things are furthere explained here: https://github.com/sarveshpro/n8n-heroku/issues/16#issuecomment-779489872

@thinkmojo just set those variables and your fine
